from __future__ import annotations

# === Environment Variable Keys ===
MODULES_ENV_VAR_KEY = "MODRIG_COMPONENTS_PATHS"
DESCRIPTORS_ENV_VAR_KEY = "MODRIG_DESCRIPTORS_PATHS"
TEMPLATES_ENV_VAR_KEY = "MODRIG_TEMPLATES_PATHS"
GRAPHS_ENV_VAR_KEY = "MODRIG_GRAPHS_PATHS"

# === File Extensions ===
DESCRIPTOR_EXTENSION = ".descriptor"
TEMPLATE_EXTENSION = ".template"
GRAPH_EXTENSION = ".dgGraph"

# === MetaClasses Types ===
RIG_TYPE = "modRig"
MODULE_TYPE = "modRigModule"
BASE_LAYER_TYPE = "modRigLayer"
MODULES_LAYER_TYPE = "modRigModulesLayer"

# === Shared MetaData Attribute Names ===
ID_ATTR = "id"
NAME_ATTR = "name"
IS_MOD_RIG_ATTR = "isModRig"
IS_ROOT_ATTR = "isRoot"
IS_COMPONENT_ATTR = "isComponent"

# === Rig MetaData Attribute Names ===
RIG_VERSION_INFO_ATTR = "versionInfo"
RIG_CONFIG_ATTR = "config"
RIG_ROOT_TRANSFORM_ATTR = "rootTransform"
RIG_CONTROL_DISPLAY_LAYER_ATTR = "controlDisplayLayer"
RIG_ROOT_SELECTION_SET_ATTR = "rootSelectionSet"
RIG_CONTROL_SELECTION_SET_ATTR = "controlSelectionSet"
RIG_JOINT_SELECTION_SET_ATTR = "jointSelectionSet"
RIG_SKELETON_SELECTION_SET_ATTR = "skeletonSelectionSet"

# === Module MetaData Attribute Names ===
MODULE_VERSION_ATTR = "version"
MODULE_SIDE_ATTR = "side"
MODULE_TYPE_ATTR = "moduleType"
MODULE_IS_ENABLED_ATTR = "enabled"
MODULE_ROOT_TRANSFORM_ATTR = "rootTransform"
MODULE_CONTAINER_ATTR = "container"
MODULE_HAS_GUIDE_ATTR = "hasGuide"
MODULE_HAS_GUIDE_CONTROLS_ATTR = "hasGuideControls"
MODULE_HAS_SKELETON_ATTR = "hasSkeleton"
MODULE_HAS_POLISHED_ATTR = "hasPolished"
MODULE_HAS_RIG_ATTR = "hasRig"
MODULE_DESCRIPTOR_ATTR = "componentDescriptor"
MODULE_GROUP_ATTR = "componentGroup"

# === Module Descriptor Attribute Names ===
DESCRIPTOR_CACHE_INFO_ATTR = f"{MODULE_DESCRIPTOR_ATTR}.DefCacheInfo"
DESCRIPTOR_CACHE_GUIDE_DAG_ATTR = (
    f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheGuideLayerDag"
)
DESCRIPTOR_CACHE_GUIDE_DG_ATTR = f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheGuideLayerDg"
DESCRIPTOR_CACHE_GUIDE_SETTINGS_ATTR = (
    f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheGuideLayerSettings"
)
DESCRIPTOR_CACHE_GUIDE_METADATA_ATTR = (
    f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheGuideLayerMetadata"
)
DESCRIPTOR_CACHE_SKELETON_DAG_ATTR = (
    f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheSkeletonLayerDag"
)
DESCRIPTOR_CACHE_SKELETON_SETTINGS_ATTR = (
    f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheSkeletonLayerSettings"
)
DESCRIPTOR_CACHE_SKELETON_METADATA_ATTR = (
    f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheSkeletonLayerMetadata"
)
DESCRIPTOR_CACHE_INPUT_DAG_ATTR = (
    f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheInputLayerDag"
)
DESCRIPTOR_CACHE_INPUT_SETTINGS_ATTR = (
    f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheInputLayerSettings"
)
DESCRIPTOR_CACHE_INPUT_METADATA_ATTR = (
    f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheInputLayerMetadata"
)
DESCRIPTOR_CACHE_OUTPUT_DAG_ATTR = (
    f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheOutputLayerDag"
)
DESCRIPTOR_CACHE_OUTPUT_SETTINGS_ATTR = (
    f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheOutputLayerSettings"
)
DESCRIPTOR_CACHE_OUTPUT_METADATA_ATTR = (
    f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheOutputLayerMetadata"
)
DESCRIPTOR_CACHE_RIG_DAG_ATTR = f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheRigLayerDag"
DESCRIPTOR_CACHE_RIG_DG_ATTR = f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheRigLayerDg"
DESCRIPTOR_CACHE_RIG_SETTINGS_ATTR = (
    f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheRigLayerSettings"
)
DESCRIPTOR_CACHE_RIG_METADATA_ATTR = (
    f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheRigLayerMetadata"
)
DESCRIPTOR_CACHE_SPACE_SWITCHING_ATTR = (
    f"{MODULE_DESCRIPTOR_ATTR}.DescriptorCacheSpaceSwitching"
)

DESCRIPTOR_CACHE_ATTR_NAMES = (
    DESCRIPTOR_CACHE_INFO_ATTR,
    DESCRIPTOR_CACHE_GUIDE_DAG_ATTR,
    DESCRIPTOR_CACHE_GUIDE_SETTINGS_ATTR,
    DESCRIPTOR_CACHE_GUIDE_METADATA_ATTR,
    DESCRIPTOR_CACHE_GUIDE_DG_ATTR,
    DESCRIPTOR_CACHE_SKELETON_DAG_ATTR,
    DESCRIPTOR_CACHE_SKELETON_SETTINGS_ATTR,
    DESCRIPTOR_CACHE_SKELETON_METADATA_ATTR,
    DESCRIPTOR_CACHE_INPUT_DAG_ATTR,
    DESCRIPTOR_CACHE_INPUT_SETTINGS_ATTR,
    DESCRIPTOR_CACHE_INPUT_METADATA_ATTR,
    DESCRIPTOR_CACHE_OUTPUT_DAG_ATTR,
    DESCRIPTOR_CACHE_OUTPUT_SETTINGS_ATTR,
    DESCRIPTOR_CACHE_OUTPUT_METADATA_ATTR,
    DESCRIPTOR_CACHE_RIG_DAG_ATTR,
    DESCRIPTOR_CACHE_RIG_DG_ATTR,
    DESCRIPTOR_CACHE_RIG_SETTINGS_ATTR,
    DESCRIPTOR_CACHE_RIG_METADATA_ATTR,
    DESCRIPTOR_CACHE_SPACE_SWITCHING_ATTR,
)

# === Layer MetaData Attribute Names ===
LAYER_EXTRA_NODES_ATTR = "extraNodes"
LAYER_ROOT_TRANSFORM_ATTR = "rootTransform"
LAYER_CONNECTORS_ATTR = "connectors"
LAYER_CONNECTOR_ID_ATTR = "connectorId"
LAYER_CONNECTOR_NODE_NAME_ATTR = "connectorNodeName"
LAYER_CONNECTOR_NODE_TYPE_ATTR = "connectorNodeType"
LAYER_CONNECTOR_CANDIDATES_ATTR = "connectorCandidates"
LAYER_CONNECTOR_CANDIDATE_NODE_ATTR = "connectorCandidateNode"
LAYER_CONNECTOR_ATTR = "connector"
LAYER_CONNECTOR_START_ATTR = "connectorStart"
LAYER_CONNECTOR_END_ATTR = "connectorEnd"
LAYER_CONNECTOR_ATTRIBUTE_HOLDER_ATTR = "connectorAttributeHolder"
LAYER_SETTING_NODES_ATTR = "settingNodes"
LAYER_SETTING_NODE_ATTR = "settingNode"
LAYER_SETTING_NAME_ATTR = "settingName"
LAYER_TAGGED_NODE_ATTR = "taggedNode"
LAYER_TAGGED_NODE_SOURCE_ATTR = "taggedNodeSource"
LAYER_TAGGED_NODE_ID_ATTR = "taggedNodeId"

# === Module Descriptor Keys ===
MODULE_VERSION_DESCRIPTOR_KEY = "descriptorVersion"
MODULE_DESCRIPTION_DESCRIPTOR_KEY = "description"
MODULE_PARENT_DESCRIPTOR_KEY = "parent"
MODULE_CONNECTIONS_DESCRIPTOR_KEY = "connections"
MODULE_DAG_DESCRIPTOR_KEY = "dag"
MODULE_DG_DESCRIPTOR_KEY = "dg"
MODULE_SETTINGS_DESCRIPTOR_KEY = "settings"
MODULE_METADATA_DESCRIPTOR_KEY = "metadata"
MODULE_NAMING_PRESET_DESCRIPTOR_KEY = "namingPreset"
MODULE_SPACE_SWITCH_DESCRIPTOR_KEY = "spaceSwitching"
MODULE_GUIDE_LAYER_DESCRIPTOR_KEY = "guideLayer"
MODULE_INPUT_LAYER_DESCRIPTOR_KEY = "inputLayer"
MODULE_OUTPUT_LAYER_DESCRIPTOR_KEY = "outputLayer"
MODULE_RIG_LAYER_DESCRIPTOR_KEY = "rigLayer"

# === Naming Preset Keys ===
DEFAULT_PRESET_NAME = "modRig"

# === Names for Standard Transform Local Attributes ===
TRANSFORM_ATTRS = ("translate", "rotate", "scale")
