name: 'tp-dcc-tools-crit'
version: '0.0.1'
author: 'Tomas Poveda'
authorEmail: 'tpovedatd@gmail.com'
description: 'CRIT Rigging package'
displayName: 'tp-dcc-tools-crit'
environment:
  PYTHONPATH:
    - '{self}'
    - '{self}/preferences'
  TPDCC_BASE_PATHS:
    - '{self}'
  TPDCC_TOOL_DEFINITION_MODULES:
    - '{self}/tp/tools/rig/crit/maya/tool.py'
  TPDCC_META_PATHS:
    - '{self}/tp/libs/rig/crit/maya/meta'
  TPDCC_COMMAND_LIB:
    - '{self}/tp/libs/rig/crit/maya/library/commands'
  TPDCC_MARKING_MENU_PATHS:
    - '{self}/tp/libs/rig/crit/maya/library/markingmenus/menus'
  TPDCC_MARKING_MENU_COMMAND_PATHS:
    - '{self}/tp/libs/rig/crit/maya/library/markingmenus/commands'
  CRIT_BUILD_SCRIPTS_PATH: "{self}/tp/libs/rig/crit/library/buildscripts"
  CRIT_NAME_PRESET_PATH: "{self}/tp/libs/rig/crit/library/naming"
  CRIT_COMPONENTS_PATHS:
    - "{self}/tp/libs/rig/crit/maya/library/components"
  CRIT_DESCRIPTORS_PATHS:
    - "{self}/tp/libs/rig/crit/maya/library/descriptors"
  CRIT_COMPONENT_MODELS_PATHS:
    - "{self}/tp/tools/rig/crit/builder/models/components"
  CRIT_UI_EDITORS_PATHS:
    - "{self}/tp/tools/rig/crit/builder/editors"
  CRIT_UI_COMMANDS_PATHS:
    - "{self}/tp/tools/rig/crit/builder/commands"
commands:
  - '{self}/startup/crit.py'