name: 'tp-dcc-tools-animation'
version: '1.0.0'
required: True
author: 'Tomas Poveda'
authorEmail: 'tpovedatd@gmail.com'
description: 'Animation tools package for tp-dcc-tools framework'
displayName: 'tp-dcc-tools Animation Tools'
environment:
  PYTHONPATH:
    - '{self}'
  TPDCC_BASE_PATHS:
    - '{self}'
  TPDCC_TOOL_DEFINITION_MODULES:
    - '{self}/tp/tools/animpicker/tool.py'