name: 'tp-dcc-mobu'
version: '1.0.0'
required: True
author: 'Tomas Poveda'
authorEmail: 'tpovedatd@gmail.com'
description: 'MotionBuilder package for tpDcc Tools framework'
displayName: 'tpDcc MotionBuilder'
environment:
  PYTHONPATH:
    - '{self}'
