import os
import sys
import inspect
import subprocess


ICON_SECTION = """
/* Auto-generated by bin2c.py */
#include <stddef.h>
{}
"""


def generate_icons_header():
    root_path = os.path.dirname(os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe()))))
    bin2c_py_file = os.path.join(root_path, 'vendor', 'bin2c', 'bin2c.py')
    icons_path = os.path.join(root_path, 'icons')
    icon_files = [icon_name for icon_name in os.listdir(icons_path) if os.path.splitext(icon_name)[-1] == '.png']
    icon_file_paths = [os.path.join(icons_path, icon_name) for icon_name in icon_files]
    out_file = os.path.join(root_path, 'include', 'icons_repo.h')

    icons_header = '#ifndef ICONS_REPO_H\n#define ICONS_REPO_H\n\n'
    for icon_file_path in icon_file_paths:
        variable_name = '{}_start'.format(os.path.basename(icon_file_path).replace('.', '_'))
        result = subprocess.run([sys.executable, bin2c_py_file, icon_file_path, variable_name], capture_output=True, text=True)
        compiled_icon = result.stdout
        icons_header += ICON_SECTION.format(compiled_icon)
    icons_header += '\n\n#endif'
    
    with open(out_file, 'w') as out:
        out.write(icons_header)


if __name__ == '__main__':
    generate_icons_header()