name: 'tp-dcc-tools-utility'
version: '1.0.0'
required: True
author: 'Tomas Poveda'
authorEmail: 'tpovedatd@gmail.com'
description: 'General Utility tools package for tp-dcc-tools framework'
displayName: 'tp-dcc-tools General Utility Tools'
environment:
  PYTHONPATH:
    - '{self}'
  TPDCC_BASE_PATHS:
    - '{self}'
  TPDCC_TOOL_DEFINITION_MODULES:
    - '{self}/tp/tools/renamer/tool.py'