name: "tp-maya"
version: "0.1.0"
author: "Tomi Poveda"
authorEmail: "tpovedatd@gmail.com"
description: "Package that contains utilities and tools for working with Autodesk Maya in the TP DCC framework."
displayName: "Tp-Maya"
commands:
  - '{self}/scripts/tp_maya.py'
documentation:
  masterDoc: "README.md"
  sourceCodeFolder: "{self}/src"
  sourceFolder: "{self}/docs"
environment:
  PYTHONPATH:
  - "{self}"
  - "{self}/src"
  TP_DCC_BASE_PATHS:
    - "{self}"
    - "{self}/src"
  TP_DCC_META_PATHS:
    - "{self}/src/tp/libs/{app}/meta"
dependencies: []
tests:
  - "{self}/tests"
