name: "tp-hub"
version: "0.1.0"
author: "Tomi Poveda"
authorEmail: "tpovedatd@gmail.com"
description: "Package that contains implementation for tp-hub"
displayName: "Tp-Hub"
commands:
  - '{self}/scripts/tp_hub.py'
documentation:
  masterDoc: "README.md"
  sourceCodeFolder: "{self}/src"
  sourceFolder: "{self}/docs"
environment:
  PYTHONPATH:
  - "{self}"
  - "{self}/src"
  TP_DCC_BASE_PATHS:
    - "{self}"
    - "{self}/src"
dependencies: []
tests:
  - "{self}/tests"
