TRIGGER_ENV = 'TPDCC_TRIGGERS_COMMAND_PATHS'
TRIGGER_ATTR_NAME = 'tpTrigger'
TRIGGER_COMMAND_TYPE_ATTR_NAME = 'tpTriggerCommandType'
TRIGGER_COMMAND_ATTR_NAME = 'tpTriggerCommand'
TRIGGER_COMMAND_CONNECT_ATTR_NAME = 'tpTriggerConnects'
MARKING_MENU_LAYOUT_EXTENSION = '.markingmenu'
TRIGGER_MENU_TYPE = 0
TRIGGER_SELECTION_TYPE = 1
