name: 'tp-dcc-toolbox'
version: '1.0.0'
required: True
author: 'Tomas Poveda'
authorEmail: 'tpovedatd@gmail.com'
description: 'Package that contains functionality to develop DCC tools'
displayName: 'tp-dcc Toolbox'
environment:
  PYTHONPATH:
    - '{self}'
  TPDCC_TOOL_DEFINITION_MODULES:
    - '{self}/tp/tools/toolbox/tool.py'
commands:
  - '{self}/startup/toolbox.py'