# TP DCC Python packages to load by this environment.

tp-bootstrap:
    version: '0.1.0'
tp-core:
    version: '0.1.0'
tp-qt:
    version: '0.1.0'
tp-maya:
    version: '0.1.0'
tp-utility-tools:
    version: '0.1.0'
