# TP DCC Python packages to load by this environment.

tp-api:
    version: '0.1.0'
tp-core:
    version: '0.1.0'
tp-preferences:
    version: '0.1.0'
tp-dcc:
    version: '0.1.0'
tp-qt:
    version: '0.1.0'
tp-hotkey-editor:
    version: '0.1.0'
tp-maya:
    version: '0.1.0'
tp-unreal:
    version: '0.1.0'
tp-rpc:
    version: '0.1.0'
tp-assets:
    version: '0.1.0'
tp-utility-tools:
    version: '0.1.0'
tp-modrig:
    version: '0.1.0'
