name: 'tp-dcc-unreal'
version: '1.0.0'
required: True
author: 'Tomas Poveda'
authorEmail: 'tpovedatd@gmail.com'
description: 'Unreal package for tpDcc Tools framework'
displayName: 'tp-dcc Unreal'
environment:
  PYTHONPATH:
    - '{self}'