name: "tp-rigging-tools"
version: "0.1.0"
author: "Tomi Poveda"
authorEmail: "tpovedatd@gmail.com"
description: "Package that contains a collection of rigging tools."
displayName: "Tp-Rigging-Tools"
commands:
  - '{self}/scripts/tp_rigging_tools.py'
documentation:
  masterDoc: "README.md"
  sourceCodeFolder: "{self}/src"
  sourceFolder: "{self}/docs"
environment:
  PYTHONPATH:
  - "{self}"
  - "{self}/src"
  TP_DCC_BASE_PATHS:
    - "{self}"
    - "{self}/src"
  TP_DCC_TOOLS:
    - "{self}/src/tp/tools/rigging/skinning_toolbox/tool.py"
    - "{self}/src/tp/tools/rigging/controls_creator/tool.py"
dependencies: []
tests:
  - "{self}/tests"
