name: 'tp-dcc-tools-rig-noddle'
version: '1.0.0'
author: 'Tomas Poveda'
authorEmail: 'tpovedatd@gmail.com'
description: ' Node base rigging framework'
displayName: 'tp-dcc-tools-rig-noddle'
environment:
  PYTHONPATH:
    - '{self}'
    - '{self}/preferences'
  TPDCC_BASE_PATHS:
    - '{self}'
  TPDCC_TOOL_DEFINITION_MODULES:
    - '{self}/tp/tools/rig/noddle/tool.py'
  TPDCC_META_PATHS:
    - '{self}/tp/libs/rig/noddle/meta'
  NODDLE_NAME_PRESET_PATH: "{self}/tp/libs/rig/noddle/naming"
  NODDLE_COMPONENTS_PATHS:
    - "{self}/tp/libs/rig/noddle/components"
  NODDLE_DESCRIPTORS_PATHS:
    - "{self}/tp/libs/rig/noddle/components"
commands:
  - '{self}/startup/noddle.py'