name: 'tp-dcc-maya'
version: '1.0.0'
required: True
author: 'Tomas Poveda'
authorEmail: 'tpovedatd@gmail.com'
description: 'Maya package for tpDcc Tools framework'
displayName: 'tpDcc Maya'
environment:
  PYTHONPATH:
    - '{self}'
  TPDCC_BASE_PATHS:
    - '{self}'
  TPDCC_TOOLS_MANAGER_PATHS:
    - '{self}/tp/maya/managers/tools.py'
commands:
  - '{self}/startup/tpmaya.py'
