"""Utils module for MetaHuman rig building.

This module provides utility functions for Maya operations and attribute management.
"""

from __future__ import annotations

from .attribute_utils import (
    ATTR_CONFIG_ALL_UNLOCKED,
    ATTR_CONFIG_FK_LIMB,
    ATTR_CONFIG_IK_LIMB,
    ATTR_CONFIG_ROTATION_ONLY,
    ATTR_CONFIG_SWITCH,
    AttributeSettings,
    TransformAttributeConfig,
    add_enum_attribute,
    add_float_attribute,
    add_string_attribute,
    cleanup_attributes,
    connect_attribute,
    disconnect_attribute,
    hide_attributes,
    lock_attributes,
    unlock_attributes,
)
from .maya_utils import (
    calculate_pole_vector_position,
    create_group,
    create_nurbs_circle,
    create_offset_group,
    create_pole_vector_locator,
    delete_history,
    delete_if_exists,
    ensure_plugin_loaded,
    find_make_node,
    freeze_transforms,
    get_children,
    get_dag_node,
    get_joint,
    get_node,
    get_parent,
    get_world_position,
    get_world_rotation,
    match_transform,
    object_exists,
    reparent_node,
    select_hierarchy,
    set_color_override,
    set_up_axis,
    set_world_position,
    set_world_rotation,
    show_confirm_dialog,
    view_along_axis,
)

__all__ = [
    # Maya utils
    "ensure_plugin_loaded",
    "object_exists",
    "delete_if_exists",
    "create_group",
    "get_parent",
    "get_children",
    "select_hierarchy",
    "reparent_node",
    "freeze_transforms",
    "delete_history",
    "match_transform",
    "get_world_position",
    "set_world_position",
    "get_world_rotation",
    "set_world_rotation",
    "set_color_override",
    "create_nurbs_circle",
    "find_make_node",
    "create_offset_group",
    "calculate_pole_vector_position",
    "create_pole_vector_locator",
    "set_up_axis",
    "view_along_axis",
    "show_confirm_dialog",
    "get_node",
    "get_dag_node",
    "get_joint",
    # Attribute utils
    "AttributeSettings",
    "TransformAttributeConfig",
    "ATTR_CONFIG_ROTATION_ONLY",
    "ATTR_CONFIG_ALL_UNLOCKED",
    "ATTR_CONFIG_FK_LIMB",
    "ATTR_CONFIG_IK_LIMB",
    "ATTR_CONFIG_SWITCH",
    "cleanup_attributes",
    "lock_attributes",
    "unlock_attributes",
    "hide_attributes",
    "add_float_attribute",
    "add_enum_attribute",
    "add_string_attribute",
    "connect_attribute",
    "disconnect_attribute",
]
