name: "tp-assets"
version: "0.1.0"
author: "Tomi Poveda"
authorEmail: "tpovedatd@gmail.com"
description: "Package Manager for tp-dcc framework."
displayName: "Tp-Assets"
commands:
  - '{self}/scripts/tp_assets.py'
documentation:
  masterDoc: "README.md"
  sourceCodeFolder: "{self}/src"
  sourceFolder: "{self}/docs"
environment:
  PYTHONPATH:
  - "{self}"
  - "{self}/src"
  TP_DCC_BASE_PATHS:
    - "{self}"
    - "{self}/src"
  TP_DCC_TOOLS:
    - "{self}/src/tp/tools"
dependencies: []
tests:
  - "{self}/tests"
