name: 'tp-dcc-core'
version: '1.0.0'
required: True
author: 'Tomas Poveda'
authorEmail: 'tpovedatd@gmail.com'
description: 'Core package for tpDcc Tools framework'
displayName: 'tpDcc Core'
environment:
  PYTHONPATH:
    - '{self}'
    - '{self}/preferences'
  TPDCC_BASE_PATHS:
    - '{self}'
  TPDCC_TOOLS_MANAGER_PATHS:
    - '{self}/tp/core/managers/tools.py'
commands:
  - '{self}/startup/core.py'
