name: 'tp-dcc-core'
version: '1.0.0'
required: True
author: 'Tomas Poveda'
authorEmail: 'tpovedatd@gmail.com'
description: 'Core package for tpDcc Tools framework'
displayName: 'tpDcc Core'
environment:
  PYTHONPATH:
    - '{self}'
commands:
  - '{self}/tp/startup/core.py'
