name: "tp-qt"
version: "0.1.0"
author: "Tomi Poveda"
authorEmail: "tpovedatd@gmail.com"
description: "Package that contains Qt related utility and custom widgets"
displayName: "Tp-Qt"
commands:
  - '{self}/scripts/tp_qt.py'
documentation:
  masterDoc: "README.md"
  sourceCodeFolder: "{self}/src"
  sourceFolder: "{self}/docs"
environment:
  PYTHONPATH:
  - "{self}"
  - "{self}/src"
  TP_DCC_BASE_PATHS:
    - "{self}"
    - "{self}/src"
dependencies: []
tests:
  - "{self}/tests"
