name: "tp-core"
version: "0.1.0"
author: "Tomi Poveda"
authorEmail: "tpovedatd@gmail.com"
description: "Package that contains core code for TP DCC framework."
displayName: "Tp-Core"
commands:
  - '{self}/scripts/tp_core.py'
documentation:
  masterDoc: "README.md"
  sourceCodeFolder: "{self}/src"
  sourceFolder: "{self}/docs"
environment:
  PYTHONPATH:
  - "{self}"
  - "{self}/src"
  TP_DCC_BASE_PATHS:
    - "{self}"
    - "{self}/src"
  TP_DCC_TOOLS:
    - "{self}/src/tp/tools/sceneinventory/tool.py"
  TP_NODEGRAPH_PACKAGE_PATHS:
    - "{self}/src/tp/libs/nodegraph/packages"
  TNM_NODE_GRAPH_EDITOR_COMMANDS:
    - "{self}/src/tp/libs/nodegraph/ui/commands"
dependencies: []
tests:
  - "{self}/tests"
