name: 'tp-dcc-tools-rig'
version: '1.0.0'
required: True
author: 'Tomas Poveda'
authorEmail: 'tpovedatd@gmail.com'
description: 'Rigging package for tp-dcc-tools framework'
displayName: 'tp-dcc-tools-rig'
environment:
  PYTHONPATH:
    - '{self}'
    - '{self}/preferences'
  TPDCC_BASE_PATHS:
    - '{self}'
  TPDCC_META_PATHS:
    - '{self}/tp/libs/rig/crit/maya/meta'
  CRIT_BUILD_SCRIPTS_PATH: "{self}/tp/libs/rig/crit/library/buildscripts"
  CRIT_NAME_PRESET_PATH: "{self}/tp/libs/rig/crit/library/naming"
  CRIT_COMPONENTS_PATHS: "{self}/tp/libs/rig/crit/maya/library/components"
  CRIT_DESCRIPTORS_PATHS: "{self}/tp/libs/rig/crit/maya/library/descriptors"
commands:
  - '{self}/startup/rig.py'