name: 'tp-dcc-tools-rig'
version: '1.0.0'
author: 'Tomas Poveda'
authorEmail: 'tpovedatd@gmail.com'
description: 'Rigging package for tp-dcc-tools framework'
displayName: 'tp-dcc-tools-rig'
environment:
  PYTHONPATH:
    - '{self}'
  TPDCC_BASE_PATHS:
    - '{self}'
  TPDCC_TOOL_DEFINITION_MODULES:
    - '{self}/tp/tools/rig/rigscript/tool.py'
    - '{self}/tp/tools/rig/crit/maya/tool.py'
  TPDCC_META_PATHS:
    - '{self}/tp/libs/rig/crit/maya/meta'
  TPDCC_COMMAND_LIB:
    - '{self}/tp/libs/rig/crit/maya/library/commands'
commands:
  - '{self}/startup/rig.py'